config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :users, only: [:show, :index] do
  	resources :invites, only: :create
  	resources :reviews
  	resources :photos
  end
  resources :invites, only: [:index, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invite.rb
class Invite < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :photo, PhotoUploader
	belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewee, class_name: "User"
  belongs_to :reviewer, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_location_and_first_name_and_last_name, :against => [:address, :first_name, :last_name],
    using: {
      :tsearch => {:prefix => true}
    }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader
  has_many :invites
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo, :address, :description])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo, :address, :description])
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
	def index
		@user_invites = Invite.where(recipient: current_user, status: 'pending')
		@accepted_invites = Invite.where(recipient: current_user, status: 'accepted').or(Invite.where(sender: current_user, status: 'accepted'))
	end

	def create
	    @user = User.find(params[:user_id])
	    @invite = Invite.new(invite_params)
	    @invite.sender = current_user
	    @invite.recipient = @user
	    @invite.status = 'pending'
		respond_to do |format|
	    	if ((@invite.date_time > Time.now + 10*180) && (@invite.location != ""))
		        @invite.save
		        format.html { redirect_to user_path(@user) }
		        format.js 
	    	else
	    		format.js { render 'date_time_location_error'}
	    	end
	    end
	end

	def update
		@invite = Invite.find(params[:id])
		@invite.update(status: 'accepted')
		if @invite.save
	      respond_to do |format|
	        format.html { redirect_to invites_path }
	        format.js
	      end
	    else
	      respond_to do |format|
	        format.html { render 'invites' }
	        format.js
	      end
	    end
	end

	def destroy
		@invite = Invite.find(params[:id])
		@invite.destroy
		respond_to do |format|
			format.html { redirect_to invites_path }
			format.js
		end
	end

	private

	def invite_params
	  params.require(:invite).permit(:location, :date_time)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def create
		@user = User.find(params[:user_id])
		@photos = params[:photo]['photo'].each do |photo|
			Photo.create(photo: photo, user: @user)
		end
		respond_to do |format|
			format.html { redirect_to user_path(@user) }
			format.js
		end
	end

	def destroy
		@photo = Photo.find(params[:id])
		@photo.destroy
		respond_to do |format|
			format.html { redirect_to user_path(current_user) }
			format.js
		end
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def create
	    @user = User.find(params[:user_id])
	    @review = Review.new(review_params)
	    @review.reviewer = current_user
	    @review.reviewee = @user
	    if @review.save
	      respond_to do |format|
	        format.html { redirect_to user_path(@user) }
	        format.js  # <-- will render `app/views/reviews/create.js.erb`
	      end
	    else
	      respond_to do |format|
	        format.html { render 'users/show' }
	        format.js  # <-- idem
	      end
	    end
	end

	def destroy
		@review = Review.find(params[:id])
		@review.destroy
		respond_to do |format|
			format.html { redirect_to user_path(@user) }
			format.js
		end
	end

	private

	def review_params
	  params.require(:review).permit(:rating, :description)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def show
		@user = User.find(params[:id])
		@invite = Invite.new
		@review = Review.new
		@invite_sent = Invite.where(recipient: @user, sender: current_user)
		@user_reviews = Review.where(reviewee: @user)
		@image = Photo.new
	end

	def index
		if params[:search]
	      @search_results_users = User.where.not(id: current_user.id).search_by_location_and_first_name_and_last_name(params[:search]).geocoded
	      respond_to do |format|
	        format.js { render partial: 'search-results'}
	      end
	    else
	      @users = User.where.not(id: current_user.id).geocoded
	    end

	    if params[:search]
	    	@markers = @search_results_users.map do |user|
		      {
		        lat: user.latitude,
		        lng: user.longitude,
		        infoWindow: render_to_string(partial: "info_window", locals: { user: user })
		      }
		    end
		else
		    @markers = @users.map do |user|
		      {
		        lat: user.latitude,
		        lng: user.longitude,
		        infoWindow: render_to_string(partial: "info_window", locals: { user: user })
		      }
		    end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/invites/_invite-sent.html.erb
<div class="invite-sent pt-2">
	<div class="text-center">
		<%= fa_icon 'check-circle 5x' %>
		<h1 class="font-weight-light p-2">Invite Sent!</h1>
	</div>
</div>

app/views/invites/create.js.erb
$('#new-invite').hide().before("<%= j render 'invite-sent' %>")

app/views/invites/date_time_location_error.js.erb
alert("Please make sure the date and time are at least 30 mins from now and the location is set!");

app/views/invites/destroy.js.erb
$('#invite-card-<%= @invite.id %>').fadeOut()

app/views/invites/index.html.erb
<section>
	<div class="container">
		<% if @accepted_invites.any? %>
			<h2 class="my-3 font-weight-light">Accepted Invites</h2>
			<hr>
			<% @accepted_invites.each do |invite| %>
				<div class="col-12 border rounded mt-3" id="invite-card-<%= invite.id %>">
					<div class="row">
						<% if invite.sender == current_user %>
							<div class="col-12 col-md-2 pt-3 text-center accepted-invite-user-profile">
								<%= link_to user_path(invite.recipient) do %>
									<img src="<%= invite.recipient.photo %>" class="rounded-circle" alt="" style="height: 60px;width: 60px;">
									<p class="lead mt-2" style="font-size: 16px;"><%= invite.recipient.first_name %> <%= invite.recipient.last_name %></p>
								<% end %>
							</div>
							<div class="col-12 col-md-8">
								<h4 class="mt-4"><%= fa_icon 'check' %> Accepted</h4>
								<p class="lead pt-3" style="font-size: 18px;">You are meeting <%= invite.recipient.first_name %> <%= invite.recipient.last_name %> at <%= invite.location %> on <%= invite.date_time.strftime("%b %e at %l:%M %p") %></p>
							</div>
							<div class="col-12 col-md-2">
								<%= link_to "Cancel", invite_path(invite), method: :delete, remote: true, class: 'btn btn-light m-4 px-4'  %>
							</div>
						<% else %>
							<div class="col-12 col-md-2 pt-3 text-center accepted-invite-user-profile">
								<%= link_to user_path(invite.sender) do %>
									<img src="<%= invite.sender.photo %>" class="rounded-circle" alt="" style="height: 60px;width: 60px;">
									<p class="lead mt-2" style="font-size: 16px;"><%= invite.sender.first_name %> <%= invite.sender.last_name %></p>
								<% end %>
							</div>
							<div class="col-12 col-md-8">
								<h4 class="mt-4"><%= fa_icon 'check' %> Accepted</h4>
								<p class="lead pt-3" style="font-size: 18px;">You are meeting <%= invite.sender.first_name %> <%= invite.sender.last_name %> at <%= invite.location %> on <%= invite.date_time.strftime("%b %e at %l:%M %p") %></p>
							</div>
							<div class="col-12 col-md-2">
								<%= link_to "Cancel", invite_path(invite), method: :delete, remote: true, class: 'btn btn-light m-4 px-4'  %>
							</div>
						<% end %>
					</div>
				</div>
			<% end %>
		<% end %>
		<h2 class="my-3 font-weight-light">Invites for <%= current_user.first_name %></h2>
		<hr>
		<div class="row">
			<% if @user_invites.empty? %>
				<h2 class="font-weight-light p-3">No New Invites</h2>
			<% else %>
				<% @user_invites.each do |invite| %>
					<div class="col-12 col-md-3" id="invite-card-<%= invite.id %>">
						<div class="card rounded-bottom mb-4">
							<div class="card-top rounded-top" style="height: 200px; background-position: center center; background-size: cover; background-image: url('<%= invite.sender.photo %>');">
							</div>
							<div class="card-content p-3">
								<div class="card-title">
									<h3 class="font-weight-light"><%= invite.sender.first_name %> <%= invite.sender.last_name %></h3>
								</div>
								<p class="lead" style="font-size: 18px;">has invited you to meet in <%= invite.location %> on <%= invite.date_time.strftime("%b %e at %l:%M %p") %></p>
								<div class="card-buttons text-center" style="display: flex; justify-content: space-between;">
									 <%= link_to "Accept", invite_path(invite, status: "accepted"), method: :patch, class: 'btn btn-dark px-4', remote: true  %>
									 <%= link_to "Decline", invite_path(invite), method: :delete, class: 'btn btn-light px-4', remote: true  %>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</section>

app/views/invites/update.js.erb
$('#invite-card-<%= @invite.id %>').fadeOut()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocializeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.4.0/mapbox-gl.css' rel='stylesheet' />
    <script src="https://kit.fontawesome.com/bfd631a3b3.js" crossorigin="anonymous"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.4.0/mapbox-gl.js'></script>
    <script src="https://cdn.jsdelivr.net/npm/places.js@1.16.5"></script>
  </head>

  <body>
    <%= render 'components/navbar' %>
    <%= yield %>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<%= render './components/banner' %>

<section class="pt-8 pt-md-11">
	<div class="container">
		<div class="row align-items-center justify-content-between mb-5 mb-md-11">
			<div class="col-12 col-md-6 order-md-2 px-5 mt-5">
				<h2 class="mb-3">Find People Near You</h2>
				<p class="font-size-lg text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime sint ullam officiis odio quam ipsam magnam, repudiandae eius perspiciatis atque, vero quia sequi, magni similique qui quaerat enim veniam modi temporibus provident expedita. Consectetur earum ipsam cumque provident totam vitae consequuntur, placeat cupiditate incidunt sit unde, aspernatur. Nemo provident consectetur perspiciatis eveniet neque ipsam</p>
			</div>
			<div class="col-12 col-md-6 p-5 order-md-1">
				<%= image_tag("undraw_location_search_bqps.svg", class: "img-fluid mw-md-150 mw-lg-130 mb-6 mb-md-0") %>
			</div>
		</div>
	</div>
</section>

<section class="pt-8 pt-md-11">
	<div class="container">
		<div class="row align-items-center justify-content-between mb-5 mb-md-11">
			<div class="col-12 col-md-6 px-5 mt-5">
				<h2 class="mb-3">Invite Them To Meet</h2>
				<p class="font-size-lg text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime sint ullam officiis odio quam ipsam magnam, repudiandae eius perspiciatis atque, vero quia sequi, magni similique qui quaerat enim veniam modi temporibus provident expedita. Consectetur earum ipsam cumque provident totam vitae consequuntur, placeat cupiditate incidunt sit unde, aspernatur. Nemo provident consectetur perspiciatis eveniet neque ipsam</p>
			</div>
			<div class="col-12 col-md-6 p-5">
				<%= image_tag("undraw_invite_i6u7.svg", class: "img-fluid mw-md-150 mw-lg-130 mb-6 mb-md-0") %>
			</div>
		</div>
	</div>
</section>

<section class="pt-8 pt-md-11">
	<div class="container">
		<div class="row align-items-center justify-content-between mb-5 mb-md-11">
			<div class="col-12 col-md-6 order-md-2 px-5 mt-5">
				<h2 class="mb-3">Meet Up</h2>
				<p class="font-size-lg text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime sint ullam officiis odio quam ipsam magnam, repudiandae eius perspiciatis atque, vero quia sequi, magni similique qui quaerat enim veniam modi temporibus provident expedita. Consectetur earum ipsam cumque provident totam vitae consequuntur, placeat cupiditate incidunt sit unde, aspernatur. Nemo provident consectetur perspiciatis eveniet neque ipsam</p>
			</div>
			<div class="col-12 col-md-6 p-5 order-md-1">
				<%= image_tag("undraw_people_tax5.svg", class: "img-fluid mw-md-150 mw-lg-130 mb-6 mb-md-0") %>
			</div>
		</div>
	</div>
</section>

app/views/photos/_images_uploaded.html.erb
<div id="upload-successful">
	<h4 class="font-weight-light">Images Uploaded</h4>
</div>

app/views/photos/create.js.erb
$('#new-images form').trigger("reset");
$('#new-images').before("<%= j render 'images_uploaded' %>")
$('#upload-successful').delay(3000).fadeOut()
$("#carouselExampleIndicators").load(" #carouselExampleIndicators");
$("#userPhotos").load(" #userPhotos");

app/views/photos/destroy.js.erb
$('#user-photo-<%= @photo.id %>').fadeOut()
$("#carouselExampleIndicators").load(" #carouselExampleIndicators");

app/views/reviews/create.js.erb
$("#user-reviews").load(location.href + " #user-reviews");
$('#new-review form').trigger("reset");

app/views/reviews/destroy.js.erb
$('#user-review-<%= @review.id %>').fadeOut()

app/views/users/_info_window.html.erb
<div class="info-window">
	<%= cl_image_tag user.photo, class: 'info-window-pic' %>
	<h5><%= user.first_name %> <%= user.last_name %></h5>
	<p><%= user.address %></p>
	<%= link_to "Go To Profile", user_path(user), class: 'btn btn-primary info-window-button'  %>
</div>

app/views/users/_results.html.erb
<% if @search_results_users.any? %>
	<div class="row">
		<% @search_results_users.each do |user| %>
			<div class="col-12 col-md-4 card-profile-link user-card">
				<%= link_to user_path(user) do %>
					<div class="card rounded-bottom mb-4">
						<div class="card-top rounded-top" style="height: 200px; background-position: center center; background-size: cover; background-image: url('<%= user.photo %>');">
						</div>
						<div class="card-content p-3">
							<div class="card-title">
								<h3 class="font-weight-light"><%= user.first_name %> <%= user.last_name %></h3>
							</div>
							<div class="card-address">
								<p class="lead"><%= user.address %></p>
							</div>
							<p class="card-description lead" style="font-size: 18px;"><%= user.description[0..100] %>...</p>
						</div>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>
<% else %>
	<h3 class="font-weight-light p-3">No Users Found</h3>
	<%= link_to "View All", users_path, class: 'btn btn-secondary ml-3 px-3'  %>
<% end %>

app/views/users/_search-results.js.erb
$('#mapCards').hide();
$('#search-results').show().html("<%= escape_javascript(render partial: 'results') %>");
$('#search-user-form').trigger("reset");

app/views/users/index.html.erb
<section class="search-and-show-hide-map">
	<div class="container" style="max-width: 100%;">
		<div class="row">
			<%= form_tag users_path, method: :get, remote: true, style: 'display: table;', id: 'search-user-form' do %>
				<div class="col-12 col-md-9" style="display: table-cell;vertical-align: middle;">
					<%= text_field_tag :search, params[:search], placeholder: 'Enter Location or Name', class: 'location-input shadow-sm' %>
				</div>
				<div class="col-12 text-center col-md-2" style="display: table-cell;vertical-align: middle;">
					<%= submit_tag "Search", class: "btn btn-primary search-button px-4" %>
				</div>
			<% end %>
			<div class="col-12 text-center text-md-left col-md-2 show-map">
				<div class="show-map-title">
					Show Map	
				</div>
				<label class="switch">
				  <input type="checkbox" id="toggleMapCheckbox" name="toggleMapCheckbox" checked>
				  <span class="slider round"></span>
				</label>
			</div>
		</div>
	</div>
</section>

<section class="pt-4 pt-md-2">
	<div class="col-12">
		<div class="row">
			<div class="col-12 col-md-7" id="mapCards">
				<div class="row">
					<% @users.each do |user| %>
						<div class="col-12 col-md-4 card-profile-link user-card">
							<%= link_to user_path(user) do %>
								<div class="card rounded-bottom mb-4">
									<div class="card-top rounded-top" style="height: 200px; background-position: center center; background-size: cover; background-image: url('<%= user.photo %>');">
									</div>
									<div class="card-content p-3">
										<div class="card-title">
											<h3 class="font-weight-light"><%= user.first_name %> <%= user.last_name %></h3>
										</div>
										<div class="card-address">
											<p class="lead mb-1"><%= user.address %></p>
										</div>
										<p class="card-description lead" style="font-size: 18px;"><%= user.description[0..100] %>...</p>
										<div class="user-rating" style="font-size: 15px;font-weight: 600">
											<%= fa_icon 'star' %>
											 <%= Review.where(reviewee: user).average(:rating).to_f.round(2) %> (<%= Review.where(reviewee: user).count.to_i %>)
										</div>
									</div>
								</div>
							<% end %>
						</div>
					<% end %>
				</div>
			</div>
			<div id="search-results" class="col-12 col-md-7" style="display: none;">

			</div>
			<div
			  class='col-md-5'
			  id="map"
			  style='position: sticky;top: 0px;overflow: hidden;height: 100vh;'
			  data-markers="<%= @markers.to_json %>"
			  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
			></div>
		</div>
	</div>
</section>




<script>
	const mapElement = document.getElementById('map');
	const fitMapToMarkers = (map, markers) => {
	const bounds = new mapboxgl.LngLatBounds();
	markers.forEach(marker => bounds.extend([ marker.lng, marker.lat ]));
	map.fitBounds(bounds, { padding: 70, maxZoom: 3 });
	};

	if (mapElement) {
	mapboxgl.accessToken = mapElement.dataset.mapboxApiKey;
	const map = new mapboxgl.Map({
	  container: 'map',
	  style: 'mapbox://styles/mapbox/streets-v10'
	});

	const markers = JSON.parse(mapElement.dataset.markers);
	markers.forEach((marker) => {
	  const popup = new mapboxgl.Popup().setHTML(marker.infoWindow);
	  new mapboxgl.Marker()
	    .setLngLat([ marker.lng, marker.lat ])
	    .setPopup(popup)
	    .addTo(map);
	});
	fitMapToMarkers(map, markers);
	}
</script>

app/views/users/show.html.erb
<section class="p-2 p-md-11">
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-5">
				<div class="user-profile-card m-3">
					<div class="user-profile-pic">
					 	<img src="<%= @user.photo %>" class="img-thumbnail" alt="<%= @user.first_name %>'s Profile Picture"> 
					</div>
					<div class="user-profile-about p-3">
						<h1 class="font-weight-light mt-3"><%= @user.first_name %> <%= @user.last_name %></h1>
						<p class="user-profile-location lead"><%= @user.address %></p>

						<div class="user-rating" style="font-size: 16px;font-weight: 600">
							<%= fa_icon 'star' %>
							 <%= Review.where(reviewee: @user).average(:rating).to_f.round(2) %> (<%= Review.where(reviewee: @user).count.to_i %>)
						</div>

						<div class="user-profile-description lead mt-3">
							<p><%= @user.description %></p>
						</div>
						<% if @user == current_user %>
							<div class="edit-user-profile py-2 d-flex mb-1">
								<%= link_to "Edit Profile", edit_user_registration_path, class: 'btn btn-secondary ml-auto'  %>
							</div>
						<% end %>
					</div>
				</div>
			</div>
			<div class="col-12 col-md-7">
				<div class="user-images mt-3">
					<% if @user.photos.any? %>
						<h1 class="font-weight-light">Gallery</h1>
						<hr>
						<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
						  <ol class="carousel-indicators">
						    <% @user.photos.each_with_index do |photo, n| %>
						    	<li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
						   <% end %>
						  </ol>
						  <div class="carousel-inner" role="listbox" style=" width:100%; height: 500px !important;">
						  	<div class="carousel-item active">
							    <%= cl_image_tag @user.photos.first.photo %>
							</div>
							<% @user.photos.drop(1).each do |photo| %>
							    <div class="carousel-item">
							       <%= cl_image_tag photo.photo %>
							    </div>
							<% end %>
						  </div>
						  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
						    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
						    <span class="sr-only">Previous</span>
						  </a>
						  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
						    <span class="carousel-control-next-icon" aria-hidden="true"></span>
						    <span class="sr-only">Next</span>
						  </a>
						</div>
					<% end %>
					<% if @user == current_user %>
						<hr>
						<div class="col-12" id="userPhotos">
							<div class="row">
								<% @user.photos.each do |photo| %>
									<div class="user-photo" id="user-photo-<%= photo.id %>">
										<div class="user-photo-top">
									    	<img src="<%= photo.photo %>" style="height: 100px;">
										</div>
										<div class="user-photo-bottom">
											<%= link_to "Delete", user_photo_path(current_user, photo), method: :delete, remote: true, class: 'btn btn-danger delete-button mt-2'  %>
										</div>
									</div>
								<% end %>
							</div>
						</div>
						<h4 class="font-weight-light mt-4">Upload New Images</h4>
						<hr>
						<div id="new-images">
							<%= simple_form_for([@user, @image], remote: true) do |f| %>
							  <%= f.input :photo, label: false, input_html: { multiple: true } %>
							  <%= f.input :photo_cache, as: :hidden %>
							  <%= f.button :submit, 'Upload', class: 'btn btn-primary px-3' %>
							<% end %>
						</div>
					<% end %>
				</div>
				<hr>
				<% if (@user != current_user) && (@invite_sent.empty?) %>
					<div id="new-invite" class="mt-2">
						<h1 class="font-weight-light">Invite <%= @user.first_name %> to Meet</h1>
						<hr>
						<%= simple_form_for([@user, @invite], remote: true) do |f| %>
						  <%= f.input :location, required: true %>
						  <%= f.input :date_time, required: true %>
						  <%= f.button :submit, class: 'btn btn-primary' %>
						<% end %>
					</div>
				<% elsif (@user != current_user) && (@invite_sent.any?)  %>
					<%= render 'invites/invite-sent' %>
				<% end %>
				<div class="user-profile-reviews" id="user-reviews">
					<h1 class="font-weight-light mt-3">Reviews</h1>
					<hr>
					<% if ((@user_reviews.empty?) && (@user != current_user)) %>
						<h4 class="font-weight-light">Be the first to leave a review</h4>
					<% elsif ((@user_reviews.empty?) && (@user == current_user)) %>
					<h4 class="font-weight-light">No Reviews</h4>
					<% else %>
						<% @user_reviews.each do |review| %>
							<div class="review" id="user-review-<%=review.id%>">
								<h6 class="mb-2"><%= review.created_at.strftime('%d %B %Y') %></h6>
								<% review.rating.times do  %>
									<%= fa_icon 'star', class: 'mb-3' %>
								<% end %>
								<div class="col-12">
									<div class="row">
										<div class="col-10">
											<p class="lead" style="font-size: 16px;"><%= review.description %></p>
										</div>
										<% if review.reviewer == current_user %>
											<div class="col-2 text-center">
												<%#= fa_icon 'edit', class: 'mx-2' %>
												<%= link_to user_review_path(@user, review), remote: true, method: :delete, style: 'color: black;' do  %>
													<%= fa_icon 'trash', class: 'mx-2' %>
												<% end %>
											</div>
										<% end %>
									</div>
								</div>

								<div class="review-user d-table">
									<%= link_to user_path(review.reviewer) do %>
										<div class="d-table-cell">
										 	<img src="<%= review.reviewer.photo %>" class="rounded-circle" alt="<%= review.reviewer.first_name %>'s Profile Picture" style="height: 50px;width: 50px;"> 
										</div>
										<div class="d-table-cell" style="vertical-align: middle;">
											<div class="ml-3">
										 		<p class="m-0" style="font-size: 14px;font-weight: 500">
										 			<%= review.reviewer.first_name %> <%= review.reviewer.last_name %></p>
										 		<p class="lead m-0" style="font-size: 12px;">Joined in <%= review.reviewer.created_at.strftime('%B %Y') %></p>
											</div>
										</div>
									<% end %>
								</div>
							<hr>
							</div>
						<% end %>
					<% end %>
				</div>
				<% if @user != current_user %>
					<div id="new-review" class="mt-5">
						<h3 class="font-weight-light">Leave a Review about <%= @user.first_name %></h3>
						<hr>
						<%= simple_form_for([@user, @review], remote: true) do |f| %>
						  <%= f.input :rating, collection: 1..5, include_blank: false %>
						  <%= f.input :description, required: true %>
						  <%= f.button :submit, class: 'btn btn-primary' %>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</section>